import { useEffect, useState } from 'react';
import { Link, Navigate, Outlet, useNavigate } from 'react-router-dom';
import { BarChart3, CalendarDays, GalleryHorizontal, LogOut, Megaphone, MessageSquare, Settings, Users } from 'lucide-react';
import { api } from '../../lib/api';

const tokenKey = 'jci_admin_token';
const navigation = [{ to: '/admin', label: 'Dashboard', icon: BarChart3 }, { to: '/admin/members', label: 'Members', icon: Users }, { to: '/admin/leadership', label: 'Leadership', icon: Users }, { to: '/admin/events', label: 'Events', icon: CalendarDays }, { to: '/admin/notices', label: 'Notices', icon: Megaphone }, { to: '/admin/gallery', label: 'Gallery', icon: GalleryHorizontal }, { to: '/admin/messages', label: 'Messages', icon: MessageSquare }, { to: '/admin/settings', label: 'Settings', icon: Settings }];
export const token = () => localStorage.getItem(tokenKey) || '';

export const AdminLogin = () => {
  const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  if (token()) return <Navigate to="/admin" replace />;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); if (!email || !password) return setError('Enter your email and password.'); setLoading(true); try { const result = await api<{ token: string }>('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); localStorage.setItem(tokenKey, result.token); navigate('/admin'); } catch (err) { setError(err instanceof Error ? err.message : 'Login failed.'); } finally { setLoading(false); } };
  return <main className="grid min-h-screen place-items-center bg-slate-100 p-4"><form onSubmit={submit} className="w-full max-w-md rounded-2xl bg-white p-8 shadow-xl"><p className="mb-2 text-sm font-bold uppercase tracking-[.2em] text-jci-gold">JCI Biratnagar</p><h1 className="mb-6 text-3xl font-bold text-jci-blue">Admin sign in</h1>{error && <p className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<label className="mb-4 block text-sm font-semibold">Email<input value={email} onChange={(e) => setEmail(e.target.value)} type="email" className="mt-1 w-full rounded-lg border p-3" autoComplete="email" /></label><label className="mb-6 block text-sm font-semibold">Password<input value={password} onChange={(e) => setPassword(e.target.value)} type="password" className="mt-1 w-full rounded-lg border p-3" autoComplete="current-password" /></label><button disabled={loading} className="btn-primary w-full">{loading ? 'Signing in…' : 'Sign in'}</button></form></main>;
};
export const AdminLayout = () => { const navigate = useNavigate(); if (!token()) return <Navigate to="/admin/login" replace />; return <div className="min-h-screen bg-slate-100 lg:grid lg:grid-cols-[240px_1fr]"><aside className="bg-jci-blue p-5 text-white"><Link to="/admin" className="mb-8 block text-xl font-bold">JCI Biratnagar<br /><span className="text-sm text-jci-gold">ADMIN PANEL</span></Link><nav className="grid grid-cols-2 gap-2 lg:grid-cols-1">{navigation.map(({ to, label, icon: Icon }) => <Link key={to} to={to} className="flex items-center gap-3 rounded-lg px-3 py-2 text-sm hover:bg-white/10"><Icon size={17} />{label}</Link>)}</nav><button onClick={() => { localStorage.removeItem(tokenKey); navigate('/admin/login'); }} className="mt-8 flex items-center gap-2 text-sm text-blue-100 hover:text-white"><LogOut size={17} />Logout</button></aside><main className="p-5 sm:p-8"><Outlet /></main></div>; };
const labels: Record<string, string> = { members: 'Members', leadership: 'Leadership', events: 'Events', notices: 'Notices', gallery: 'Gallery', messages: 'Contact Messages' };
export const Dashboard = () => { const [stats, setStats] = useState<Record<string, number>>({}); const [error, setError] = useState(''); useEffect(() => { api<Record<string, number>>('/dashboard', {}, token()).then(setStats).catch((e) => setError(e.message)); }, []); return <><h1 className="mb-6 text-3xl font-bold text-jci-blue">Dashboard</h1>{error ? <p className="rounded-lg bg-red-50 p-4 text-red-700">{error}</p> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(stats).map(([key, value]) => <div key={key} className="rounded-xl bg-white p-5 shadow-sm"><p className="text-sm font-semibold capitalize text-slate-500">{key.replace(/([A-Z])/g, ' $1')}</p><p className="mt-2 text-3xl font-bold text-jci-blue">{value}</p></div>)}</div>}</> };
export const ResourcePage = ({ resource }: { resource: string }) => { const [items, setItems] = useState<Record<string, unknown>[]>([]); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [title, setTitle] = useState(''); const load = () => api<Record<string, unknown>[]>(`/${resource}/admin`, {}, token()).then(setItems).catch((e) => setError(e.message)); useEffect(() => { void load(); }, [resource]); const create = async (e: React.FormEvent) => { e.preventDefault(); if (!title.trim()) return; try { await api(`/${resource}`, { method: 'POST', body: JSON.stringify(resource === 'members' || resource === 'leadership' ? { name: title, category: resource === 'leadership' ? 'Leadership' : 'Member' } : { title, ...(resource === 'notices' ? { content: title } : {}) }) }, token()); setTitle(''); void load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to create record.'); } }; const remove = async (id: string) => { if (!confirm('Delete this record?')) return; await api(`/${resource}/${id}`, { method: 'DELETE' }, token()); void load(); }; const filtered = items.filter((item) => JSON.stringify(item).toLowerCase().includes(query.toLowerCase())); return <><h1 className="mb-6 text-3xl font-bold text-jci-blue">{labels[resource]}</h1><form onSubmit={create} className="mb-6 flex flex-col gap-3 rounded-xl bg-white p-4 shadow-sm sm:flex-row"><input value={title} onChange={(e) => setTitle(e.target.value)} className="flex-1 rounded-lg border p-3" placeholder={`New ${labels[resource]?.slice(0, -1) || resource} name/title`} /><button className="btn-primary">Add</button></form><input value={query} onChange={(e) => setQuery(e.target.value)} className="mb-4 w-full rounded-lg border p-3" placeholder="Search…" />{error && <p className="mb-4 text-red-700">{error}</p>}<div className="overflow-x-auto rounded-xl bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">Name / title</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody>{filtered.map((item) => <tr key={String(item._id)} className="border-t"><td className="p-4 font-semibold">{String(item.name || item.title || item.email || 'Untitled')}</td><td className="p-4">{String(item.status || item.published || '')}</td><td className="p-4"><button onClick={() => remove(String(item._id))} className="text-red-600">Delete</button></td></tr>)}</tbody></table></div></> };
export const SettingsPage = () => <ResourcePage resource="settings" />;
